import tkinter as tk
root = tk.Tk()
root.title("Sistema de Busqueda de Personas")
root.geometry("400x300") 
label = tk.Label(root, text= "Agregar Persona")
label.pack()
button = tk.Button(root, text= "Agregar")
button.pack()
root.mainloop()
print("hola mundo")
root.mainloop()